### ISSUE TITLE
smart-cursorline do not work correctly

### ISSUE THREAD

**Issue by lancelock** [liuchengxu/space-vim#183]
#### Environment

- OS: archlinux
- vim: 8.0
- neovim: no

#### Problem Description

the config smart-cursorline do not work right, when i enter insert mode ,it set nocursorline,but when i return to normal mode ,command `set cursorline` does not work. is that normal?

In addition, i think this config can also set to toggle cursor style between insert mode and  normal mode. i mean , in insert mode ,turn i-beam ; i normal mode, turn block. and in iterm2@macos ,it appears like this.but in gnome-teruminal@archlinux, the cursor style will not change,what is the reason?

**Comment by liuchengxu** [comment]
Yes, it's intentional. When you enter insert mode and leave some window, `set nocursorline`. When you leave insert mode and enter some window, `set cursorline`, see https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bdistributions/better-defaults/config.vim#L4-L8 . If you don't like the current setting, reset it in `UserConfig()`:

```vim
augroup spacevimCursorline
  autocmd!
augroup END
```

FYI, the change of cursor shape in iterm2 has been supported, see https://github.com/liuchengxu/vim-better-default/blob/master/plugin/default.vim#L103-L123 . Refer to [Change cursor shape in different modes](http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes) for more details. Since macOS is my daily use, I haven't tested the related config under other OS. If interested, you can have a try with gnome-terminal.

**Comment by lancelock** [comment]
i see,thanks

by the way , why my neovim does't  support？ 

i have run this command `ln -s ~/.space-vim/init.vim ~/.config/nvim/init.vim`, but it has no changes

**Comment by liuchengxu** [comment]
You mean space-vim doesn't work in neovim? It should run smoothly in neovim.

**Comment by lancelock** [comment]
yes , it  does not change anything
and if i has no vim in my system ,i cant install space-vim,i must install vim first
os: archlinux - 4.11.7-1
neovim: 0.2.0

**Comment by liuchengxu** [comment]
Try this:

```sh
# Install space-vim for both Vim and NeoVim
curl -L https://raw.githubusercontent.com/liuchengxu/space-vim/installation/install.sh | sh -s -- all

# Only install space-vim for Vim
curl -L https://raw.githubusercontent.com/liuchengxu/space-vim/installation/install.sh | sh -s -- vim

# Only install space-vim for NeoVim
curl -L https://raw.githubusercontent.com/liuchengxu/space-vim/installation/install.sh | sh -s -- neovim
```

**Comment by lancelock** [comment]
really thanks! i have resolve this problem via use the third command. i want to know if vim and neovim now use the same config?

and then how can i add python3 support for neovim?

i have got the prompt `[deoplete] It requires Neovim with Python3 support("+python3")`

**Comment by liuchengxu** [comment]
Yes, Vim and NeoVim will use the same config.

deoplete requires Neovim with if_python3.

```sh
pip3 install neovim
```

**Comment by lancelock** [comment]
thanks i have no more problem
