### ISSUE TITLE
Plugin recommendation:vim-leader-guide

### ISSUE THREAD

**Issue by tracyone** [liuchengxu/space-vim#34]
[vim-leader-guide](https://github.com/hecal3/vim-leader-guide)

Spacemacs like function:displays the available key bindings **automatically** and **dynamically**.

No need any config.

```viml
#suppose  leader is space
nnoremap <silent> <leader> :<c-u>LeaderGuide '<Space>'<CR>
vnoremap <silent> <leader> :<c-u>LeaderGuideVisual '<Space>'<CR>
```

**Comment by liuchengxu** [comment]
Actually, I have tried this plugin before. However, I don't think it is good enough to play an important role in the daily use at present. It seemingly can't give a **real-time** prompt like helm in spacemacs，which is very important.  Furthermore, the help information of key bindings needs to be well organized so that we can get a good experience in using, which also needs some works to be done. 

For now, I suggest putting it in private plugins. But we can keep this issue open, it may be good enough someday.

**Comment by zer4tul** [comment]
i've made a preview branch, maybe you can have a try. https://github.com/zer4tul/space-vim/tree/heavy

**Comment by liuchengxu** [comment]
@zer4tul  Wow, it really looks pretty heavy!  I'll give it a try.

**Comment by fno2010** [comment]
I also tried **vim-leader-guide**, and I think it should be useful. If you are used to using spacemacs with evil, **which-key** is very helpful. But the difference between vim and evil maybe the **leader key timeout**. Many vimers like to set leader timeout.

For example, in vim, I can bind `<leader>b` and `<leader>bn` to different functions. But in evil, if I bind `<leader>bn`, the `<leader>b` will be a group and I cannot bind `<leader>b`.

Any thoughts?

**Comment by fno2010** [comment]
@zer4tul: just checked your [heavy](https://github.com/zer4tul/space-vim/tree/heavy) branch. It is really what I wanted when I started to try space-vim. But the same question as my above comment, is it possible to handle leader timeout very well?

@liuchengxu Have you tried @zer4tul 's branch? It should be more similar with spacemacs. If you are just looking for something like the `which-key` in spacemacs, I think it is not bad. You can see the screenshot:

![2017-01-06-233238_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4464757/21722692/aeaa1ddc-d468-11e6-8982-138f0087cb70.png)

But you can see that `<leader>qm` and `<leader>qQ` cannot be grouped, because `<leader>q` is also mapped.

**Comment by zer4tul** [comment]
i've noticed that. but i didn't find out a solution. maybe we should fork leader-guide to solve this.

**Comment by liuchengxu** [comment]
I have tried the heavy branch (Still, I think that the leader guide is good, but not enough. Even `SPC q` is not speedy like before). 

Maybe we can make a new branch focusing on this? It's a really major revision and some problems really exist. I suggest integrating this into space-vim slowly.  In order to bring in vim-leader-guide eventually, some good plans have to be made too.

With so much contented added, I don't think space-vim is simple any more 😂 。

**Comment by liuchengxu** [comment]
@zer4tul  I have just made a new branch named `vim-leader-guide` based on the most recent master branch. Could you merge the heavy branch (or the part you think is ready) into it? Then we can all have a look and do something together.

**Comment by zer4tul** [comment]
Initial version done. i have sent the PR.

**Comment by liuchengxu** [comment]
Accepted.

**Comment by zer4tul** [comment]
well, it's OK for me. i want to make a leader-guide layer, so those ones who don't need the prompt can easily disable it.

**Comment by liuchengxu** [comment]
@zer4tul Thanks, I have sent the invitation.

**Comment by liuchengxu** [comment]
I have pushed a commit to vim-leader-guide branch.

- Since we intend to make leader-guide a layer, we could source core_keybindings.vim in the layer config.
- Disable `SPC q [qQs]` temporarily until find a solution.
- Improve lightline/config.vim.

**Comment by liuchengxu** [comment]
@zer4tul I have a problem:

<img width="1277" alt="2017-01-13 3 40 26" src="https://cloud.githubusercontent.com/assets/8850248/21921958/a767c50e-d9a6-11e6-8a8d-0f2f461eeb28.png">

I configure vim-leader-guide in `UserConfig()` : 
```vim
    let g:lmap =  {}

    let g:lmap['a'] = { 'name' : '+align' }
    let g:lmap['b'] = { 'name' : '+buffer' }
    ......
```
vim-leader-guide doesn't show me the name `+align` (actually the whole help information doesn't work), but the keymappings is seemingly normal.

<img width="1277" alt="2017-01-13 3 42 32" src="https://cloud.githubusercontent.com/assets/8850248/21922009/eef2b7d0-d9a6-11e6-9b3d-9ea122bdfaae.png">

If we can add the brief description to the existing key mappings shown in vim-leader-guide, maybe a lot of works could be saved.

**Comment by zer4tul** [comment]
这周跟下周都会比较忙，年底，你懂的。这个问题等我忙过这段时间看一下，有进展我会回复。

**Comment by liuchengxu** [comment]
了然了然，顺其自然，正事要紧

**Comment by ctjhoa** [comment]
Hi there,
I just find out about this repo, I've got [my spacevim](https://github.com/ctjhoa/spacevim) for quit a while now. I have `vim-leader-guide` support and I ve already faced [this issue](https://github.com/ctjhoa/spacevim/issues/32).
It looks like a `vim-leader-guide` bug to me, using [this particular version](https://github.com/hecal3/vim-leader-guide/tree/bade1b9dfc5e56aaf322791fff11e350fd8681ae) fix the problem. Unfortunately I don't have time to dig deeper in this now.

**Comment by liuchengxu** [comment]
@ctjhoa Thanks! [spacevim](https://github.com/ctjhoa/spacevim) is also a good job.

It seems that to switch [the particular version](https://github.com/hecal3/vim-leader-guide/tree/bade1b9dfc5e56aaf322791fff11e350fd8681ae) could not fix the problem in my case, it raises some other errors:

```vim
Error detected while processing function leaderGuide#start_by_prefix:
line    6:
E121: Undefined variable: s:cached_dicts
E116: Invalid arguments for function has_key(s:cached_dicts, a:key) || g:leaderGuide_run_map_on_popup
E15: Invalid expression: !has_key(s:cached_dicts, a:key) || g:leaderGuide_run_map_on_popup
line   12:
E121: Undefined variable: s:desc_lookup
E116: Invalid arguments for function has_key(s:desc_lookup, a:key) || has_key(s:desc_lookup , 'top')
E15: Invalid expression: has_key(s:desc_lookup, a:key) || has_key(s:desc_lookup , 'top')
line   18:
E121: Undefined variable: rundict
E116: Invalid arguments for function <SNR>149_start_buffer
Press ENTER or type command to continue
```
I will dig into this when I have time。BTW, since [spacevim](https://github.com/ctjhoa/spacevim) has supported vim-leader-guide, are you positive on helping [space-vim](https://github.com/liuchengxu/space-vim) make a leader-guide Layer? Maybe we have the same goals, which is to switch from emacs to vim painlessly. I'm also a spacemacs user and vimmer.

**Comment by tracyone** [comment]
I just made a ctrlp extension :[ctrlp-leader-guide](https://github.com/tracyone/ctrlp-leader-guide)😄

**Comment by liuchengxu** [comment]
@tracyone Uh, it looks not bad, but maybe not the ultimate goal.

**Comment by tracyone** [comment]
another similar plugin: [sunaku/vim-shortcut](https://github.com/sunaku/vim-shortcut)

**Comment by liuchengxu** [comment]
It looks good. I'll give it a try.

**Comment by ctjhoa** [comment]
@liuchengxu I've done some progress on the `vim-leader-guide` issue (https://github.com/hecal3/vim-leader-guide/issues/39). I'm not against merging the effort it's just that I'm really busy, I will try to take a look at your integration ASAP.

**Comment by liuchengxu** [comment]
@ctjhoa Great! Thanks a lot! I'm still working on this.
