### ISSUE TITLE
output errors from install.sh

### ISSUE THREAD

**Issue by ossphil** [liuchengxu/space-vim#48]
install.sh gave the following errors during executation:

```shell
± |master U:2 ?:1 ✗| → ./install.sh
Attempting to back up your original vim configuration.
/Users/hui/.vimrc -> /Users/hui/.vimrc.20170115_1484473485
[✔] Your original vim configuration has been backed up.
==> Trying to update space-vim
From https://github.com/liuchengxu/space-vim
 * branch            master     -> FETCH_HEAD
Already up-to-date.
[✔] Successfully updated space-vim
[✔] Setting up vim symlinks.


Press ENTER or type command to continue
/bin/sh: ./install--all: No such file or directory

shell returned 127

Press ENTER or type command to continue
[✔] Now updating/installing plugins using vim-plug

Thanks for installing space-vim. Enjoy!
```

It seems that space-vim was installed successfully, but what's the errors?

Thanks

**Comment by liuchengxu** [comment]
It's caused by [install of fzf](https://github.com/junegunn/fzf/blob/master/install), and you could just ignore it, the error doesn't matter. 

I didn't take a closer look at [install of fzf](https://github.com/junegunn/fzf/blob/master/install), this error should only appear when you update space-vim (more accurately, update fzf in space-vim), not install it at the first time.
