### ISSUE TITLE
Which version/branch of the space-vim  is more update? 

### ISSUE THREAD

**Issue by iihawk** [liuchengxu/space-vim#64]
I found 3 space-vim sites:
(1) https://github.com/liuchengxu/space-vim
(2) https://github.com/SpaceVim/SpaceVim
(3) https://spacevim.org/

Are they maintained by the same group of people? and all are about the same thing?
Which version of them is more update?

screenshot of site(2) look more fancy, but after installing, the vim did not look like the screenshots.
and it stucks. but I'd like to have the configurations for the screenshots, How to get it?

I successfully installed space-vim from site(1), it does look beautiful, Thanks for your efforts!

**Comment by liuchengxu** [comment]
site(1) and site(2) is mutually independent. They are maintained by different people and developed with quite different purposes, although they all claim that they got inspired by [spacemacs](https://github.com/syl20bnr/spacemacs).

For site(1) https://github.com/liuchengxu/space-vim , since I am both a vimmer and a spacemacs user, it remains lots of elements from [spacemacs](https://github.com/syl20bnr/spacemacs), e.g., the whole architecture, GUI and key bindings. It's of great convenience for those using vim and spacemacs at the same time.

For site(2) https://github.com/SpaceVim/SpaceVim, except its name, I think it is more useful for pure vimmers.

(3) https://spacevim.org/ is merely the website of site(2).
