### ISSUE TITLE
how to display icon in statusline when using macvim?

### ISSUE THREAD

**Issue by zhenjun115** [liuchengxu/space-vim#88]
<img width="301" alt="2017-03-09 9 40 46" src="https://cloud.githubusercontent.com/assets/5096364/23732213/b92bd0ec-04ac-11e7-833a-6201a27e17f9.png">

**Comment by zhenjun115** [comment]
<img width="301" alt="2017-03-09 9 40 46" src="https://cloud.githubusercontent.com/assets/5096364/23732187/97c8aa2e-04ac-11e7-8352-d449a517618d.png">

**Comment by liuchengxu** [comment]
Actually, you can use any Unicode characters you like. However, due to the rendering issue in MacVim, some Unicode characters can't be displayed well.

<img width="53" alt="2017-03-09 9 51 06" src="https://cloud.githubusercontent.com/assets/8850248/23732421/fd48afd8-04ad-11e7-90ff-92f768fe1217.png">

I don't know If you can put up with this?

**Comment by zhenjun115** [comment]
It is wired that macvim can not render these unicode characters but iterm2 can, should i ask the question at macvim repo ?

**Comment by liuchengxu** [comment]
https://github.com/vim/vim/issues/732 

It seems that we could do nothing about this.

**Comment by zhenjun115** [comment]
maybe, space-vim can load the layer statusline when use macvim to avoid

**Comment by liuchengxu** [comment]
#92, some people are interested in the statusline of space-vim, I'm considering exacting the statusline part to make a seperate plugin, maybe.

**Comment by zhenjun115** [comment]
statusline used by space-vim is beautiful.
